channels:
  - conda-forge
  - bioconda
  - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public
dependencies:
  - snakemake-minimal >=9.7.1
  - jinja2
  - matplotlib
  - graphviz
  - fsl-avwutils
  - fsl-flirt
