[workspace]
name = "brainhack-snakemake"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
channels = ["conda-forge", "bioconda"]

[dependencies]
python = "3.11.*"
snakemake-minimal = ">=8.0"
jinja2 = "*"
matplotlib = "*"
graphviz = "*"
nilearn = ">=0.10.0"
nibabel = "*"
numpy = "*"