[project]
name = "brainhack-snakemake"
channels = ["conda-forge", "bioconda", "https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "3.11.*"
snakemake-minimal = ">=8.0"
jinja2 = "*"
matplotlib = "*"
graphviz = "*"
fsl-avwutils = "*"
fsl-flirt = "*"