[workspace]
name = "brainhack-snakemake"
platforms = ["linux-64", "osx-64", "osx-arm64"]
channels = ["conda-forge", "bioconda", "https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public"]

[dependencies]
python = "3.11.*"
snakemake-minimal = ">=9.7.1"
jinja2 = "*"
matplotlib = "*"
graphviz = "*"
fsl-avwutils = "*"
fsl-flirt = "*"